version: '2'
services:
  web: &app_base
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - APP_HOME=${PWD}
    ports:
     - "3000:3000"
    command: rails s -p 3000 -b 0.0.0.0
    links:
      - db
      - redis
    volumes:
      - .:${PWD}
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD:
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379
  spring:
    <<: *app_base
    ports: [] 
    command: spring server
    stdin_open: true
    tty: true
    pid: host
    environment:
      SPRING_SOCKET: /tmp/spring/spring.sock
    volumes:
      - .:${PWD}
      - spring_volume:/tmp/spring
  db:
    image: postgres
    ports:
      - "5432"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  react:
    image: node:latest
    ports:
      - '4000:4000'
    build:
      context: ./react_server
      dockerfile: ./react_server/Dockerfile.development
      args:
        - REACT_HOME=${PWD}/react_server
volumes:
  spring_volume:
